[versions]
coroutines = "1.10.2"
dokka = "2.1.0"
kotest = "6.0.7"
ksp = "2.3.4"
kotlin = "2.2.21"
arrow = "2.2.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-frameworkEngine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }